### ISSUE TITLE
Bullet points

### ISSUE THREAD

**Issue by MallyT** [chrismsimpson/Metropolis#10]
Hi there,   
Just wondering if Metropolis is likely to have bullet points added to Glyphs? 
Thank you

**Comment by ayaoconnor** [comment]
Hi @chrissimpson,

I'm wondering the same. Do you have plans to add bullet points (circular and/or square) to this family? Love the typeface -- just need this functionality given the content I'm working with.

Thanks!

**Comment by chrismsimpson** [comment]
Circle bullet is already in there
