### ISSUE TITLE
Left quotation marks (german)

### ISSUE THREAD

**Issue by jankoob** [chrismsimpson/Metropolis#11]
Hey,

I really like using your font!
Just missing german left single and double quotes (Unicode 201A, 201E).

**‚A‘**

**„A“**

**Comment by iminarik** [comment]
Hi I second this request. Double left quotation marks would be highly appreciated. Otherwise the font is perfect!
Thanks

**Comment by konzeptklar** [comment]
I also second the request. Please integrate the 
*Double Low-9 Quotation Mark – Unicode 201E*

=>  „

Thanks!

**Comment by konzeptklar** [comment]
Thanks for adding the „ in the straigt styles.

For the **italics** it's mixed up with the "comma" = ,

**Comment by chrismsimpson** [comment]
Fix, coming in release 11 :)
