### ISSUE TITLE
Degree symbol (°), Greek characters and fractions

### ISSUE THREAD

**Issue by TenKWS** [chrismsimpson/Metropolis#12]
Hey!

I love your font, it's a very nice alternative to Gotham (naming in on point!), but I foung out that the degree symbol is missing.

Also, it would be nice to have Greek characters included as well as fractions. It would make the font much more professional and usable.

Thank you!
Kevin

**Comment by chrismsimpson** [comment]
Degree symbol coming in release 11 :)
