### ISSUE TITLE
Line height weirdness

### ISSUE THREAD

**Issue by artivity** [chrismsimpson/Metropolis#13]
Appears to be some extra spacing below the characters. Especially apparent when using as a web font for things like navigation, buttons etc which have line-height specified. Possibly just the way the web fonts were converted? Obviously can be rectified manually with CSS, but would be nice to be able to have it a bit more universal so to speak?

**Comment by chrismsimpson** [comment]
No, I suspect this more of and underlying issue with the set up of the metrics, which means it's going to be very hard to fix :(

**Comment by dothem1337** [comment]
Any fix on this? Or any workaround?

**Comment by chrismsimpson** [comment]
Have clean up a bunch of stuff, try the new release/exports :)
