### ISSUE TITLE
Google Fonts – request

### ISSUE THREAD

**Issue by paulvantuyl** [chrismsimpson/Metropolis#14]
Hi is it possible to add Metropolis to Google Fonts so I can sync it via Skyfonts?

**Comment by podrivo** [comment]
This would be awesome! 💯 
These are the requirements: https://github.com/google/fonts/blob/master/CONTRIBUTING.md

**Comment by chrismsimpson** [comment]
If someone can verify that Metropolis adheres to Google Font's contribution criteria and all I have to do is submit it, I'd be more than happy to. If there's any nontrivial work required (and I suspect there might be) then I'm afraid it's a no from my until someone can submit a PR with all the changes needed to comply. I'm afraid this is not high priority for me.

Not to dissuade you, if you can do the due diligence yourself I'm always happy to accept PRs to Metropolis :)

**Comment by podrivo** [comment]
There's already an issue to include Metropolis: https://github.com/google/fonts/issues/676

**Comment by davelab6** [comment]
I manage the Google Fonts library. Great to see you are open to collaboration, that's what we are all about! :) 

Would you be willing to remove the RFN from the license file? Then we can proceed :)

**Comment by readeral** [comment]
@chrismsimpson as much as someone can make the change to the license file and submit a pull request... changing a license is a bit different to making technical changes! Are you amenable to a license change before someone goes and does it?

**Comment by felipesanches** [comment]
@chrismsimpson, please confirm that you are OK with the removal of "Reserved Font Name". This is a tweak to the licensing terms, so it requires your explicit authorization.

**Comment by chrismsimpson** [comment]
Yep, that’s fine.. just create the pr and I’ll merge :)

**Comment by felipesanches** [comment]
OK. I am working on this.
I have prepared a Travis build setup that installs fontmake, gftools and fontbakery and then performs the build of the font sources and runs the quality checks with FontBakery.

Before a font can be added to the Google Fonts collection, the FontBakery check results should contain no `FAIL`s and we should at least review the `WARN` messages.

This is the log of the first build with this new setup: 
https://travis-ci.com/felipesanches/Metropolis/builds/132235996

Ss you can see in the bottom of the log, we still got a couple hundred FAILs to fix:
<img width="151" alt="Captura de Tela 2019-10-16 às 18 06 26" src="https://user-images.githubusercontent.com/213676/66958922-b1511e00-f03f-11e9-984f-c082d8868cee.png">

I will be gradually fixing those by making changes that (ideally) do not significantly change the actual glyph outlines.

**Comment by felipesanches** [comment]
Please close issue #23, which is redundant to this one.

**Comment by felipesanches** [comment]
Every time I push new commits trying to fix some of the Font Bakery reported FAILs, a new build runs on Travis. You can monitor the build at https://travis-ci.com/felipesanches/Metropolis/builds/

With the few fixes I've just pushed to my `issue_14` branch (https://github.com/felipesanches/Metropolis/tree/issue_14), we are now with 110 FAILs yet to be addressed.

I hope my messages here are helpful to showcase the "test-driven development" workflow we have been using to tackle quality assurance of fonts.

**Comment by chrismsimpson** [comment]
What kind of errors are these? Also, what is this build generated from, OTF, TTF or Glyphs (or other)?

**Comment by felipesanches** [comment]
The build is generated from `Sources/*.glyphs`

The FAILs being fixed are the results of the quality checks form the `googlefonts` profile on Font Bakery. Those checks are described at https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html

Further info (including an overview of our quality assurance strategies) are available at the Font Bakery documentation, at: https://font-bakery.readthedocs.io/en/latest/index.html

**Comment by readeral** [comment]
Thanks so much for putting this work in @felipesanches and for your agreement @chrismsimpson - hopefully the end result is satisfactory for adding to google fonts!

**Comment by podrivo** [comment]
I'm glad to see this is going forward. Thanks @felipesanches! 👍

**Comment by felipesanches** [comment]
Cheers!

You should keep the issue open, though ;-)

**Comment by jfranconi** [comment]
I see this is closed but I dont see this in Google Fonts yet.

**Comment by christianmagill** [comment]
Excited to see this is happening. Any idea on typical timeframe?

**Comment by felipesanches** [comment]
There's no guarantee that the font will ever be added to the Google Fonts collection. The work being done here is a proposal to add it, and an effort to address technical issues detected by the quality assurance tools. Once the font project is in a good state from a font engineering perspective, then it is up to Google to review the submission and decide whether or not the font is a good fit for the GFonts collection. I have no control over that final decision. I am here only helping you to improve the project's technical quality.

@chrismsimpson still needs to review and merge the PR at #35 and this issue here should actually be open so that we can keep track of progress.

**Comment by jfranconi** [comment]
@felipesanches  If this isnt for tracking the actual merge into Google Fonts collection is there a separate request for that being tracked or no?

**Comment by kriiv** [comment]
How's this tracking? Anything I can do to help?

**Comment by drawcard** [comment]
I'd love me some Metropolis too!
