### ISSUE TITLE
Backtick Character ` overwrites the next character

### ISSUE THREAD

**Issue by adityarb88** [chrismsimpson/Metropolis#15]
**Issue:** The backtick character ` overwrites the next character when we use the Metropolis font.

![image](https://user-images.githubusercontent.com/1426805/31522254-e831893a-af7a-11e7-979f-6518e1eafe74.png)

**Reproduction of the Issue:** https://plnkr.co/edit/sqv3j5yfSoSJk778hFd4?p=preview

**More info here:** https://github.com/vmware/clarity/issues/1521

@chrismsimpson: Could you please let us know if this is an issue with the font or if its the webfont conversion process that might be causing this?

Thanks!

**Comment by adityarb88** [comment]
Also noticed that if I type multiple backticks, they overlap each other:

`<p>```````````` This line should show multiple backticks</p>`

This renders like this:
![image](https://user-images.githubusercontent.com/1426805/31950919-b9156cbe-b8aa-11e7-944f-1f1a7f7593e9.png)

**Comment by chrismsimpson** [comment]
Just had a quick look in glyphs and the OTF derived version (in Sketch) and backticks seem fine. This must be an export issue. Can you confirm which format?

**Comment by adityarb88** [comment]
@chrismsimpson: We use font squirrel to convert the fonts you provide to `WOFF2` format. These are the settings we use but I also tried other combinations but couldn't find one that would solve this issue.

![image](https://user-images.githubusercontent.com/1426805/32791216-7fcd9348-c92e-11e7-8594-d31b1d5ef4ec.png)

**Comment by digitalh2o2** [comment]
Any updates to this? Noticing the same issues.

**Comment by chrismsimpson** [comment]
<img width="948" alt="Screen Shot 2020-02-01 at 10 31 10 pm" src="https://user-images.githubusercontent.com/2238758/73591467-cf855000-4542-11ea-83ef-0c9ed0f04081.png">

<img width="951" alt="Screen Shot 2020-02-01 at 10 32 54 pm" src="https://user-images.githubusercontent.com/2238758/73591468-d57b3100-4542-11ea-8daa-65818d57f824.png">

Should now be fixed in new release, enjoy! :)
