### ISSUE TITLE
Request for ‘General Punctuation’ characters

### ISSUE THREAD

**Issue by timothymctim** [chrismsimpson/Metropolis#2]
I was wondering if you could add more characters from the ‘General Punctuation’ code block (`U+2000`–`U+206F`) to your font. In particular, I was looking for `U+202F NARROW NO-BREAK SPACE`, but if I'm not mistaken it's missing right now.

I love this font, looks really great, and I'm glad you put this under an open license!

**Comment by chrismsimpson** [comment]
Hi Timothy,

Certainly, I'm happy to get that done for you. I'm currently on a trip and don't have my set up with me, but I'll have a look at it as soon as I get back at the end of the month.

Chris.

**Comment by timothymctim** [comment]
Cool! Thanks for your quick reply. No need to rush to fix feature request for me :)

**Comment by chrismsimpson** [comment]
Done (plus a bunch of extra punctuation)

**Comment by timothymctim** [comment]
Wauw, great! Thanks a lot.
Did you deliberately choose to make `U+202F NARROW NO-BREAK SPACE` as wide as a normal space? I am afraid to say that I believe `U+00A0 NO-BREAK SPACE` should be used for that.

**Comment by chrismsimpson** [comment]
Hey Timothy,

How wide in your view do you think U+202F should be?

Cheers,
C.

On Nov 08, 2016, at 10:01 AM, timothymctim <notifications@github.com> wrote:

Wauw, great! Thanks a lot.
Did you deliberately choose to make U+202F NARROW NO-BREAK SPACE as wide as a normal space? I am afraid to say that I believe U+00A0 NO-BREAK SPACE should be used for that.

**Comment by timothymctim** [comment]
I want to start with saying that I'm not an expert on this topic, but consulted some references to try to help.

The Unicode standard indicates that [U+202F](http://www.fileformat.info/info/unicode/char/202f/index.htm) is “a narrow form of a no-break space, typically the width of a thin space or a mid space.”
A thin space [U+2009](http://www.fileformat.info/info/unicode/char/2009/index.htm) has as comment that it is “a fifth of an em (or sometimes a sixth).”
A mid space [U+2005](http://www.fileformat.info/info/unicode/char/2005/index.htm) is one-fourth of an em space.
Also Wikipedia contains on [whitespace characters](https://en.wikipedia.org/wiki/Whitespace_character) a nice reference.

If the width of an em space ([U+2003](http://www.fileformat.info/info/unicode/char/2003/index.htm)) is 1000, then—following the guidelines—the width of U+202F could be anything within 166–250. I personally would go for the size of a thin space at one-fifth of an em, e.g., 200, or maybe even a bit smaller since the “regular” space seems to be “only” 290 units wide.

_A small side note: both the en dash and the em dash seems to have a different width compared to the en space and em space, respectively._

For comparison, I have looked up the widths used by DejaVu Sans. Here both the em space and em dash is 2048 units wide and U+202F is 409, identical to the width of a thin space. A mid space ([U+2005 FOUR-PER-EM SPACE](http://www.fileformat.info/info/unicode/char/2005/index.htm)) is 512 and a “regular” space [U+0020](http://www.fileformat.info/info/unicode/char/0020/index.htm) is 651 units wide.
