### ISSUE TITLE
Missing Slovak characters

### ISSUE THREAD

**Issue by tomasmayer** [chrismsimpson/Metropolis#21]
Hello, can you please add some characters for slovak language?
Specifically: capital č (Č), š (Š), ľ (Ľ), ť (Ť), ž (Ž), ý (Ý), á (Á), í (Í), é (É). Also small ĺ (small L with ´).
Thank you.

**Comment by tomasmayer** [comment]
Also you can add § symbol. Thank you.

**Comment by akolmacka** [comment]
Hi, I'm using this font with Czech characters (Á, É, Ě, Í, Ý, Ú, Ů, Č, Š, Ž, Ť) and it works for me. I also tried Ľ ľ and it works as well.

**Comment by tomasmayer** [comment]
Oh, but I don't see it correctly in Word 2016. Just see C without ˇ.

**Comment by akolmacka** [comment]
Sorry, I never used this font in Word. I just tried it and I have same problem there.

**Comment by chrismsimpson** [comment]
These glyphs are definitely there. Try the latest export.
