### ISSUE TITLE
Add package.json...?

### ISSUE THREAD

**Issue by tfrommen** [chrismsimpson/Metropolis#22]
Hey there,

what do you think about adding a `package.json` file so people are able to use this very cool font via the [npm registry](https://www.npmjs.com/)? This has been done for other fonts too, for example, the very popular [Fira Code](https://github.com/tonsky/FiraCode/commit/d0181db077c9d9aa13c2e9d07bad0320a773ea5a).

I can send a PR, if you want. However, there are a few things we'd need to clarify first.

### `name`
Unfortunately, there already is a `metropolis` project in the registry, so we could either find another name for it (e.g., `metropolis-font`, `metropolis-typeface` etc.) or use a prefix ( e.g., `@chrismsimpson/metropolis` or something else).
Any preference?

### `version`
Since projects should adhere to [Semantic Versioning](https://semver.org/), you would need to start releasing actual **versions**, instead of arbitrary _releases_. I suggest to take the current _release_ number, add one, and make it the major of the actual semantic version; this would mean the next version is `10.0.0`).
Of course, you could also choose any other arbitrary version number such as `1.0.0` or `2.0.0` (if you see the adoption of SemVer as a major change). Or take the current release, and make the next one a minor or patch release, meaning `9.1.0` or `9.0.1`, respectively. Depending on what you think you did in the [8 commits](https://github.com/chrismsimpson/Metropolis/compare/r9...master) since the last release.
What should it be?

### `license` (as in the file)
In order for npm to be able to pick up licensing information you would need to rename the file that includes your license (i.e., `Open Font License.md`) to something like `LICENSE.md` or just `LICENSE`.

### `files` (aka _Contents_)
Project using the npm registry (i.e., usually web stuff) do not need all there is in this source repository. So, I suggest to only include the web fonts. But this is just me.
What do you think?

---

A **possible** `package.json` file could therefore look like so:

```json
{
  "name": "@chrismsimpson/metropolis",
  "version": "10.0.0",
  "description": "Metropolis: A modern, geometric typeface.",
  "keywords": [
    "font",
    "type",
    "typeface",
    "metropolis",
    "geometric",
    "modern"
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/chrismsimpson/Metropolis"
  },
  "author": "Chris Simpson",
  "license": "OFL-1.1",
  "bugs": {
    "url": "https://github.com/chrismsimpson/Metropolis/issues"
  },
  "homepage": "https://github.com/chrismsimpson/Metropolis",
  "files": [
    "Webfonts"
  ]
}
```

Thoughts?

**Comment by locness3** [comment]
@tfrommen

**Comment by chrismsimpson** [comment]
Added, closing this issue :)
