### ISSUE TITLE
GoogleFonts QA

### ISSUE THREAD

**Issue by m4rc1e** [chrismsimpson/Metropolis#23]
For Google Fonts to host this family, we'd need the following changes.

[Metropolis FB Report](http://35.225.170.228/report/799a5be6-6a7b-441b-85ed-8137ad54ce2a).(ignore the Validator tests, they're all false positives)

You can test your fonts against our requirements using our online QA tool, [fontbakery](http://35.225.170.228)

I understand you're busy and this may be waaay down on your list of priorities.

Nice family btw.

**Comment by m4rc1e** [comment]
Ahh sorry I just read https://github.com/chrismsimpson/Metropolis/issues/14#issuecomment-343899683.

**Comment by felipesanches** [comment]
This can now be closed as we'll continue this conversation on issue #14
