### ISSUE TITLE
poor kerning for capital T

### ISSUE THREAD

**Issue by jeffjohnson** [chrismsimpson/Metropolis#24]
Kerning for the capital T needs adjustment. I am sure there are others, such as kerning for the capital L (and likely other capital letters).

See the example image, which compares Metropolis to Helvetica (because it is widely used and appreciated). The red line indicates the rightmost pixel of the left-hand glyph. The green line indicates the leftmost pixel of the right-hand glyph.

Notice that the spacing is consistent with Metropolis, but it doesn't look good. Very noticeable when you combine `T` and `o` to form **To**. Also very noticeable with the capital `L` when set against the capital `T`. There is simply too much space.

By contrast, with Helvetica, the `o` glyph is partially underneath the `T` glyph. There is a lack of consistency with Helvetica, as can be evidenced by the **Tc** and **Tg** combinations (it seems that only vowels have custom kerning with the letter T).

Perhaps there is significant kerning that needs to be adjusted for Metropolis? Love this font, btw.

![kerning](https://user-images.githubusercontent.com/180477/39642231-0c1842ac-4f9f-11e8-8e2a-8de1eb276579.gif)

**Comment by chrismsimpson** [comment]
You've hit the nail on the head, all the spacing and kerning needs redoing. Spacing is done, now the massive job of kerning... 😓

**Comment by jeffjohnson** [comment]
What can I do to help you? I am familiar with Fontforge, but that doesn't look like the format you are using.

**Comment by chrismsimpson** [comment]
<img width="768" alt="Screen Shot 2020-02-01 at 10 29 13 pm" src="https://user-images.githubusercontent.com/2238758/73591399-4706af80-4542-11ea-9b16-d1edfad55eb9.png">

This is fixed in release 10, enjoy! :)
