### ISSUE TITLE
Missing Bullet points 

### ISSUE THREAD

**Issue by elenafranck** [chrismsimpson/Metropolis#27]
Hi Chris, 

@chrismsimpson I would really appreciate it if you'd consider adding bullet points to this glyph set. A simple circle or square would really go a long way in this typeface's usability for my purposes. Thanks!!

**Comment by sdurnov** [comment]
Duplicate of https://github.com/chrismsimpson/Metropolis/issues/10

**Comment by chrismsimpson** [comment]
Circle bullet is in there :)
