### ISSUE TITLE
Ascender and descender in Xcode

### ISSUE THREAD

**Issue by vash88** [chrismsimpson/Metropolis#30]
The ascender and descender offset in Xcode is being ignored so the line height is way too tight. This seems to be a pretty common problem with how Xcode handles custom fonts. For personal use I'm using a line height of 135% by setting the ascender to 1000 and the descender to -350 using FontForge. It might be worth looking into using the font in Xcode to see the results you get.

Discussion around the issue for other fonts: https://stackoverflow.com/questions/5414730/custom-installed-font-not-displayed-correctly-in-uilabel

**Comment by chrismsimpson** [comment]
I _think_ this is related to TTF, and not the typeface specifically. As it's Xcode, try the OTF export instead.
