### ISSUE TITLE
Modern G

### ISSUE THREAD

**Issue by KodedScorpius** [chrismsimpson/Metropolis#31]
Suggestion:

![image](https://user-images.githubusercontent.com/43486313/56464991-e8ad7d80-63c2-11e9-98ce-655cc48e4e30.png)

Create uppercase G just like that! Everything else looks almost the same, except the G with the bump.

**Comment by alexandergunnarson** [comment]
Just chiming in as an interested party — I think it might be nice as a character alternate but I wouldn't make it the primary capital G. I've always liked the perpendicularity of Gotham's (and thus Metropolis's) G. In my opinion it contributes to the soothing uniformity of its uppercase letters. If Metropolis were to have a fully-rounded geometric sans capital G à la Futura, it would break with the character of the rest of the font, I think.

**Comment by MeteorCoder** [comment]
> Just chiming in as an interested party — I think it might be nice as a character alternate but I wouldn't make it the primary capital G. I've always liked the perpendicularity of Gotham's (and thus Metropolis's) G. In my opinion it contributes to the soothing uniformity of its uppercase letters. If Metropolis were to have a fully-rounded geometric sans capital G à la Futura, it would break with the character of the rest of the font, I think.

Are you saying that one can just copy the assets from the regular font, change the G, then make it something like `RegularAlt`, instead of totally overriding the default G? If so, I'm up 🙂

**Comment by alexandergunnarson** [comment]
Haven't played around with glyph / character set manipulation recently but that seems like a reasonable approach. Not sure it would be accepted by @chrismsimpson though, since the geometric sans G you're describing is out of character of Metropolis.

**Comment by FloraCanou** [comment]
An entire alternative typeface would add to unnecessary complication. OpenType feature is good enough for this purpose.

**Comment by alexandergunnarson** [comment]
Sorry, I misread what @MeteorCoder was saying; thought he was saying to add an alternate glyph but yeah `copy the assets from the regular font` seems a bit much

**Comment by MeteorCoder** [comment]
Agreed! Alt G would be good.

**Comment by chrismsimpson** [comment]
This is a upper case 'G' without a 'spur'. This can be achieved with what are called 'alternates'. Remember though, to add a character, it has to be drawn 6 times (Light, Regular, Bold, Light Italic, Regular Italic & Bold Italic). Sorry, this is low on my priority list.

**Comment by gmosx** [comment]
Offering this as an `alternate`, would make Metropolis a *perfect* replacement for Google Sans. Really hope you will eventually find the time to add this!

**Comment by chrismsimpson** [comment]
Meanwhile, take a look at [Neukolln](http://github.com/chrismsimpson/Neukolln)...
