### ISSUE TITLE
Thin, ThinItalic font variant does not show up in Linux apps (wrong metadata?)

### ISSUE THREAD

**Issue by artjomsimon** [chrismsimpson/Metropolis#33]
This is seemingly related to #5:

The Thin, ThinItalic font variant does not show up in Linux apps (LibreOffice, Inkscape, ...)

Instead, I see this in the font variant selection list:
![font-weight-thin](https://user-images.githubusercontent.com/2609170/62058614-055b1c00-b222-11e9-8ef6-a4f24e034f47.png)

Maybe this helps: opening the file `Metropolis-Thin.otf` with `fontforge`, I get the following 2 warnings:

```
Warning: Mac string is a subset of the Windows string in the 'name' table for the Family string in the English (US) language.
Warning: Mac and Windows entries in the 'name' table differ for the Styles (SubFamily) string in the language English (US)
  Mac String: Thin
  Windows String: Regular
```
Don't know if that's related however.

**Comment by chrismsimpson** [comment]
I have changed the name of the masters, which I suspect may have been causing some issues here. Please try the new exports and re-open this issue if problem remains. Closing for now.
