### ISSUE TITLE
Lowercase "g" doesn't sit on the baseline

### ISSUE THREAD

**Issue by orffen** [chrismsimpson/Metropolis#4]
The shape of the lowercase "g" doesn't quite line up with the "p"/"q" glyphs. Is this intentional?

**Comment by chrismsimpson** [comment]
Hi Steve,

I’m afraid I don’t follow..


Cheers,
Chris.

**Comment by orffen** [comment]
Sorry Chris, here's an image:
![pgq](https://cloud.githubusercontent.com/assets/2225985/21035108/cbb77d8e-be10-11e6-937e-c87c51f97dfc.png)

**Comment by chrismsimpson** [comment]
Ahh.. yes, this is intentional..

**Comment by orffen** [comment]
Then I'll close the issue, cheers! :)
