### ISSUE TITLE
Word and PowerPoint: PDF font embedding issue

### ISSUE THREAD

**Issue by core-process** [chrismsimpson/Metropolis#41]
Hey Chris,
Thanks for this awesome font. We love it and use it in most of our documents!

Hey all!
There is one issue with Word and PowerPoint on Windows, though. We installed the OTF files of Metropolis on Windows 10. When we use the "Save As ➜ Format: PDF" functionality of Word and PowerPoint, both tools convert Metropolis to bitmaps. According to the Windows Fonts dialog, Metropolis is embeddable. Therefore we have no clue why that is happening. Attached, you will find a DOCX and the corresponding PDF file. Is that an issue with our systems only, or is that reproducible behavior?
Regards, Niklas

[Metropolis_Test.docx](https://github.com/chrismsimpson/Metropolis/files/4913639/Metropolis_Test.docx)
[Metropolis_Test.pdf](https://github.com/chrismsimpson/Metropolis/files/4913641/Metropolis_Test.pdf)

![Capture](https://user-images.githubusercontent.com/1226918/87326898-a1655c80-c533-11ea-8a30-6d49a3aac794.PNG)

**Comment by zzColin** [comment]
I used to have the same experience with other otf fonts. It seems that Microsoft Office never supported embedding otf fonts into PDF documents.

**Comment by core-process** [comment]
@zzColin wow, thanks! I can confirm it works with the `.ttf` fonts!
